server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://pre.mysql.001.master.hualala.com:3306/db_yuanbao?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: user_yuanbao
    password: xWpwYTYTlkM3